version: '3.8'

#volumes:
#  redis-data:
#    null
services:
  epics-pva:
    build:
      context: ../
      dockerfile: docker/Dockerfile.epics_ci_cd
    command: 
        - /bin/bash
        - -c
        - |
          tmux new-session -d "softIocPVA -d /app/epics-test.db"
          tmux new-session -d "python /app/k2eg-mailbox-server.py"
          tmux new-session -d "python /app/update_iocs.py"
          tail -f /dev/null

  epics_updater:
    platform: linux/amd64
    image: python:3.10
    command: 
        - /bin/bash
        - -c
        - |
          apt update
          apt install -y tmux
          pip install --upgrade pip
          pip install numpy p4p pyepics
          tmux new-session -d "python3 /app/update_iocs.py"
          tail -f /dev/null
    volumes:
      - ../test:/app

  consul:
    image: consul:1.15
    ports:
      - "8500:8500"  # Consul HTTP API and UI
      - "8600:8600/udp"  # DNS interface (if needed)
    command: agent -dev -ui -client=0.0.0.0
    volumes:
      - consul_data:/consul/data  # Optional persistent storage for Consul data

  kafka:
    # platform: linux/amd64
    image: apache/kafka:4.1.0
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 1

  mongodb-primary:
    image: ghcr.io/zcube/bitnami-compat/mongodb:6.0.5
    restart: on-failure
    environment:
      - MONGODB_ROOT_USER=admin
      - MONGODB_ROOT_PASSWORD=admin
      - BITNAMI_DEBUG=true
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-primary
      - MONGODB_REPLICA_SET_KEY=replicasetkey123
    ports:
      - "27017:27017"
      
volumes:
  kafka-data:
  consul_data:
