version: '3.8'

#volumes:
#  redis-data:
#    null
services:
  epics-pva:
    image: ghcr.io/epics-containers/epics-base-linux-developer:7.0.9ec3
    command: 
        - /bin/bash
        - -c
        - |
          apt update && apt install -y tmux python3 python3-pip
          pip install numpy p4p pyepics
          tmux new-session -d "softIocPVA -d /app/epics-test.db"
          tmux new-session -d "python /app/k2eg-mailbox-server.py"
          tmux new-session -d "python /app/update_iocs.py"
          tail -f /dev/null

  zookeeper:
    image: bitnami/zookeeper:3.8.1
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    logging:
      driver: none

  kafka:
    image: bitnami/kafka:3.4.0
    ports:
      - 9092:9092
      - 9093:9093
    environment:
      - BITNAMI_DEBUG=yes
      - KAFKA_BROKER_ID=1
      - KAFKA_ENABLE_KRAFT=no
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka:9092,EXTERNAL://localhost:9093
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=CLIENT
    volumes:
      - kafka-data:/bitnami/kafka
    depends_on:
      - zookeeper
    logging:
      driver: none

volumes:
  kafka-data: