version: '3.8'

#volumes:
#  redis-data:
#    null
services:
  epics-pva:
    build:
      context: ../
      dockerfile: docker/Dockerfile.epics_ci_cd
    command: 
        - /bin/bash
        - -c
        - |
          tmux new-session -d "softIocPVA -d /app/epics-test.db"
          tmux new-session -d "python /app/k2eg-mailbox-server.py"
          tmux new-session -d "python /app/update_iocs.py"
          tail -f /dev/null

  epics_updater:
    platform: linux/amd64
    image: python:3.10
    command: 
        - /bin/bash
        - -c
        - |
          apt update
          apt install -y tmux
          pip install --upgrade pip
          pip install numpy p4p pyepics
          tmux new-session -d "python3 /app/update_iocs.py"
          tail -f /dev/null
    volumes:
      - ../test:/app

  consul:
    image: consul:1.15
    ports:
      - "8500:8500"  # Consul HTTP API and UI
      - "8600:8600/udp"  # DNS interface (if needed)
    command: agent -dev -ui -client=0.0.0.0
    volumes:
      - consul_data:/consul/data  # Optional persistent storage for Consul data

  zookeeper:
    image: bitnami/zookeeper:3.9.0
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: bitnami/kafka:3.9.0
    ports:
      - 9092:9092
      - 9093:9093
    environment:
      - BITNAMI_DEBUG=yes
      - KAFKA_BROKER_ID=1
      - KAFKA_ENABLE_KRAFT=no
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka:9092,EXTERNAL://localhost:9093
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=CLIENT
    volumes:
      - kafka-data:/bitnami/kafka
    depends_on:
      - zookeeper

  mongodb-primary:
    image: ghcr.io/zcube/bitnami-compat/mongodb:6.0.5
    restart: on-failure
    environment:
      - MONGODB_ROOT_USER=admin
      - MONGODB_ROOT_PASSWORD=admin
      - BITNAMI_DEBUG=true
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-primary
      - MONGODB_REPLICA_SET_KEY=replicasetkey123
    ports:
      - "27017:27017"
      
volumes:
  kafka-data:
  consul_data: