FROM --platform=linux/amd64 ghcr.io/epics-containers/epics-base-linux-developer:7.0.7ec3
RUN apt update && apt install -y tmux
RUN pip install numpy p4p pyepics
RUN COPY ../ /app
CMD ["tail", "-f", "/dev/null"]