name: Cleanup Untagged Images

on:
  # every sunday at 00:00
  schedule:
    - cron: "0 * * * *"
  # or manually
  workflow_dispatch:

jobs:
  delete-untagged-images:
    name: Delete Untagged Images
    runs-on: ubuntu-latest
    steps:
      - name: Prune
        uses: vlaurin/action-ghcr-prune@v0.5.0
        with:
          token: ${{ secrets.YOUR_TOKEN }}
          organization: your-org
          container: your-container
          dry-run: true # Dry-run first, then change to `false`
          keep-younger-than: 7 # days
          keep-last: 2
          prune-untagged: true