name: Delete old container images
on:
  # schedule:
  #   - cron: "0 0 1 * *"  # every day at midnight
  workflow_dispatch:

jobs:
  delete-k2eg-ubuntu-untagged-images:
    name: Delete Untagged Images
    runs-on: ubuntu-latest
    steps:
      - uses: bots-house/ghcr-delete-image-action@v1.1.0
        with:
          # NOTE: at now only orgs is supported
          owner: slaclab
          name: k2eg/ubuntu
          # Keep latest N untagged images
          untagged-keep-latest: 3
          token: ${{ secrets.DELETE_PACKAGES_TOKEN }}
  delete-k2eg-debian-untagged-images:
    name: Delete Untagged Images
    runs-on: ubuntu-latest
    steps:
      - uses: bots-house/ghcr-delete-image-action@v1.1.0
        with:
          # NOTE: at now only orgs is supported
          owner: slaclab
          name: k2eg/debian
          # Keep latest N untagged images
          untagged-keep-latest: 3
          token: ${{ secrets.DELETE_PACKAGES_TOKEN }}