on:
    workflow_dispatch:
    schedule:
      - cron: "5 * * * *"  # every hour
jobs:
  docker-hub-retention:
    runs-on: [ubuntu-latest]
    steps:
        - uses: actions/delete-package-versions@v5
          with: 
            owner: 'slaclab'
            package-name: 'k2eg/ubuntu'
            package-type: 'docker'
            token: ${{ secrets.DELETE_PACKAGES_TOKEN }}
            min-versions-to-keep: 10
            delete-only-untagged-versions: 'true'